language: php

sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-source --no-interaction

script:
  - phpunit

notifications:
  email:
    on_success: never
    on_failure: change